### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest_docs#1]
We have to choose a license. Suggestions so far:

* LGPLv2.1 (like Minetest and implicitly the existing `lua_api.txt`)
* MIT (should be compatible with LGPLv2.1)
* CC BY 4.0
* CC BY-SA 4.0

My personal preference would be MIT.

**Comment by rollerozxa** [comment]
Just realised [the proposal](https://gist.github.com/benrob0329/df3ced15dc5a2d5402010be709452f27) mentions it to be licensed under CC BY 4.0.

**Comment by appgurueu** [comment]
Closing this, as the CC-BY 4.0 license text has been pushed in https://github.com/minetest/minetest_docs/commit/590352f1fe16a9e0ba88f7dbe71d80a2be7d5ce1 to comply with the proposal.

**Comment by rubenwardy** [comment]
The license will need to be LGPL if you want to copy anything from lua_api.txt
