### ISSUE TITLE
Build instructions are missing

### ISSUE THREAD

**Issue by erlehmann** [minetest/minetest_docs#22]
It is entirely unclear to me how to build this project.

I am pretty sure the build is just a few commands, but it is not documented.

**Comment by JosiahWI** [comment]
We could add something to the README.md about running AsciiDoctor or setting up VSCode plugins. We don't have any build system yet other than that.

**Comment by erlehmann** [comment]
@JosiahWI adding a few lines about how to invoke AsciiDoctor and where to find it would help indeed.

**Comment by benrob0329** [comment]
There is no build system in place yet, so no build instructions to give. We currently have some intended targets on the TODO, but nothing actually set up for that yet.

**Comment by JosiahWI** [comment]
Closing as not applicable since we don't have build instructions yet.
