### ISSUE TITLE
Relicense to CC-BY-SA (3.0/4.0?)

### ISSUE THREAD

**Issue by rollerozxa** [minetest/minetest_docs#50]
The choice of CC-BY 4.0 for this project was short sighted as all other current documentation (Minetest engine doc/ including `lua_api.txt` and the Minetest Wiki) are licensed under CC-BY-SA 3.0. We should relicense to CC-BY-SA (3.0/4.0?) so we can make use of these resources for the project.

**Comment by appgurueu** [comment]
I support this. Considering we've all read `lua_api.txt`, it is likely that our work already is a derivative (even if we wrote docs from scratch by reading the code, which in the long term is too inefficient). We *need* to be able to base our work off of `lua_api.txt` in a legally sound way in the future to move at a faster pace and allow PRs like https://github.com/minetest/minetest_docs/pull/49, which is not possible with the current license.

**Comment by wsor4035** [comment]
i support this as well

**Comment by benrob0329** [comment]
Already mentioned in the Discord, but I support this.

**Comment by Minetest-j45** [comment]
I support this too.

**Comment by appgurueu** [comment]
I give my explicit permission to relicense my contributions to CC-BY-SA 3.0.

We still need explicit permission (in no particular order) from @GreenXenith, @wsor4035, @benrob0329, @Minetest-j45 and @JosiahWI (all our contributors).

**Comment by Minetest-j45** [comment]
I also give my explicit permission to relicense my contributions to this project to CC-BY-SA 3.0.

**Comment by wsor4035** [comment]
people who have actually contributed to the repo safety agree check
* [ ] wsor
* [ ] lmd
* [ ] j45
* [ ] JosiahWi
* [ ] benrob
* [ ] greenxenith

**Comment by wsor4035** [comment]
I give my explicit permission to relicense my contributions to this project to CC-BY-SA 3.0.

**Comment by JosiahWI** [comment]
I also give my explicit permission to relicense my contributions to this project to CC-BY-SA 3.0.

**Comment by GreenXenith** [comment]
I give my explicit permission to relicense my contributions to this project to CC-BY-SA 3.0.

**Comment by benrob0329** [comment]
I give my explicit permission to relicense my contributions to this project to CC-BY-SA 3.0.

**Comment by appgurueu** [comment]
Done: https://github.com/minetest/minetest_docs/commit/5ec1cfa5430c69e85db5618174f907c0c3a3179e
